#-------------------------------
# Site Settings
title: Jishnu's Systems Immunology Lab
description: Gerous is a modern portfolio Jekyll theme
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Team"
      url: "/Team/"
    - title: "Resources"
      submenu:
      - url: "/posts/the-psychology-of-mobile-app-colors-influencing-user-perception"
        title: "News"
      - url: "/posts/gamifying-the-user-experience-strategies-beyond-mobile-games"
        title: "Games"
      - url: "/posts/harmonizing-aesthetics-and-functionality-in-ux-ui-mobile-design"
        title: "Mobile"
      - url: "/elements/"
        title: "Elements"
    - title: "Contact us"
      url: "/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Author Settings
author:
  author_name: "Welcome to Jishnu Lab"
  author_avatar: "/images/das_head.webp"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Machine Learning, Networks, Immunology, Coffee and Music
  hero_description: Leveraging our expertise, we engage in both pioneering method development and the practical application of these methods to address diverse biological challenges!

# Hero Logos
hero_logos:
  enable: true

hero_logo_image:
  - alt: "Apple Logo"
    image: "/images/ai-svgrepo-com.svg"

  - alt: "Adobe Logo"
    image: "/images/imm-svgrepo-com.svg"

  - alt: "HP Logo"
    image: "/images/deep-learning-svgrepo-com.svg"

  - alt: "Netlify Logo"
    image: "/images/coffee-cup-tea-svgrepo-com.svg"

  - alt: "Dropbox Logo"
    image: "/images/robot-ai-svgrepo-com.svg"

  - alt: "EA Logo"
    image: "/images/imm-svgrepo-com.svg"

  - alt: "Chrome Logo"
    image: "/images/immune-system-immunity-defense-svgrepo-com.svg"


#-------------------------------
# Slider Featured Settings
featured:
  enable: true
  featured_title: Selected Work


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Recent Work
  projects_description:


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: true
  testimonials_intro: Some famous quotes of our lab
  testimonials_title: See what our lab members say...
  testimonials_info: Join for over <b>10K+</b> famous lab quotes

testimonial_items:
  - name: "Swapnil Keshri"
    image: "/images/swapnil.webp"
    designation: "CPCB Phd Student"
    title: "Major update coming soon"
    content : "As a dynamic and ever-growing laboratory, we actively engage with a diverse array of research challenges presented to us. We are committed to maximizing our efforts to derive optimal outcomes from each endeavor."

  - name: "Javad Rahimikollu"
    image: "/images/javad.webp"
    designation: "CPCB Phd Student"
    title: "Try running SLIDE on your data...."
    content : "The members of our lab developed a first-in-class interpretable machine learning technique for identifying significant interacting latent factors underlying outcomes of interest from high-dimensional omic datasets which we apply on most of our datasets."

  - name: "Simar Yadav"
    image: "/images/simar.webp"
    designation: "Research Scholar"
    title: "Manchester United is the best premier league Team!!"
    content : "Manchester United has a rich history and a strong tradition in English football. The club has a storied past, filled with numerous titles, legendary players, and iconic moments.All of us consider this a fact"

  - name: "Jishnu Das"
    image: "/images/Jishnu-Das-2.jpg"
    designation: "Principal Investigator, Assistant Professor"
    title: "Do you want an espresso??"
    content : "Before engaging in a robust discussion with Jishnu, it's become a customary ritual for us to graciously accept the coffee he generously offers."


#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Frequently asked questions
  faq_intro: Need some answers?
  faq_items:
    - title: What distinguishes you as a mobile developer?
      description: I bring a wealth of experience in crafting seamless user experiences and developing mobile solutions that prioritize functionality and innovation.
    - title: How do you approach designing user-friendly mobile applications?
      description: My approach involves a user-centric design philosophy, focusing on intuitive interfaces and fluid interactions to enhance the overall mobile experience.
    - title: Can you walk us through your mobile app development process?
      description: Certainly! From concept to deployment, I follow a structured development process, incorporating user feedback and iterative testing to ensure a polished and functional mobile application.
    - title: How do you stay updated on the latest trends mobile development?
      description: Continuous learning is key. I stay updated through industry publications, attending conferences, and actively participating in professional communities to stay at the forefront of industry trends.
    - title: How do you ensure the security of mobile applications you develop?
      description: Security is a top priority. I follow industry best practices, conduct thorough testing, and implement robust security measures to safeguard mobile applications and user data.
    - title: What role does user feedback play in your development process?
      description: User feedback is integral. I actively seek and incorporate user insights to refine designs and optimize mobile applications, ensuring they align with user expectations and preferences.


#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "Hi there üëã ! Welcome to Jishnu's Systems Immunology Lab. We're a vibrant community passionate about both science and coffee."
  author_section_description: "As a computational systems immunology lab, our research focuses on the development and use of novel systems approaches to analyze high-dimensional immunological datasets, and elucidate molecular mechanisms of immunological disorders. We are currently working on using network systems and functional genomic approaches to perform multi-scale integration of genomic and epigenomic datasets with biological networks to identify molecular phenotypes underlying these immunological disorders. We also use statistical and machine-learning techniques to integrate multi-omic datasets (genomic, transcriptomic, proteomic, metabolomic and antibody-omic) and elucidate molecular mechanisms of immune regulation and dysregulation."
  author_section_image: "/images/lab_photo.JPG"
  author_section_image_alt: Daryl Mercer
  author_section_button_text: Let's —Åonnect!
  author_section_button_link: "/contact/"


#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Posts'
      url: '/posts/'
    - url: '/about/'
      title: 'About Me'

# Social Links
social:
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://www.tiktok.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Stay inspired weekly üì¨ Your friendly dose of tips & insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: Gerous comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Gerous theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
